# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CubScout < Formula
  desc "Explore and map GitOps in your clusters"
  homepage "https://confighub.com"
  version "0.19.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/confighub/cub-scout/releases/download/v0.19.3/cub-scout_0.19.3_darwin_amd64.tar.gz"
      sha256 "771b505e6040ea306d3d93ace2c6ccc3c8906230dbbf994dcd06fa44c4443ade"

      def install
        bin.install "cub-scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/confighub/cub-scout/releases/download/v0.19.3/cub-scout_0.19.3_darwin_arm64.tar.gz"
      sha256 "77fe9a7fc7c604977d11a4c1a47575138bbadb5fb9773ef8c0d6c74663bbd82d"

      def install
        bin.install "cub-scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/confighub/cub-scout/releases/download/v0.19.3/cub-scout_0.19.3_linux_amd64.tar.gz"
      sha256 "ffdf455095f0059378b7ed636f87dc3a9e25ea5c4493c46519667bc2b7197135"
      def install
        bin.install "cub-scout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/confighub/cub-scout/releases/download/v0.19.3/cub-scout_0.19.3_linux_arm64.tar.gz"
      sha256 "6cd154392364d7794f8f5c8a15aa42947890b7deca6166aec819eefeb7e9ad06"
      def install
        bin.install "cub-scout"
      end
    end
  end

  test do
    system "#{bin}/cub-scout", "version"
  end
end
