# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CubScout < Formula
  desc "Explore and map GitOps in your clusters"
  homepage "https://confighub.com"
  version "0.20.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/confighub/cub-scout/releases/download/v0.20.1/cub-scout_0.20.1_darwin_amd64.tar.gz"
      sha256 "377eab14b00bdfb7a896f3638a85a79dfbd8ef3b3eb9cfe1f99954366ff7468b"

      def install
        bin.install "cub-scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/confighub/cub-scout/releases/download/v0.20.1/cub-scout_0.20.1_darwin_arm64.tar.gz"
      sha256 "c1ff8910d780a6d326a42df5ed2ecbc8955da24856f783610a9dadf127378cb0"

      def install
        bin.install "cub-scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/confighub/cub-scout/releases/download/v0.20.1/cub-scout_0.20.1_linux_amd64.tar.gz"
      sha256 "21ce1a3db899b3e31e10daa93de9bbda6ce696d0776b72df8a8e32e66d38035d"
      def install
        bin.install "cub-scout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/confighub/cub-scout/releases/download/v0.20.1/cub-scout_0.20.1_linux_arm64.tar.gz"
      sha256 "b689a2fc3909a91a3e2569c7da9fb9921bbe7a292df7c25d02f0efcf11a1036d"
      def install
        bin.install "cub-scout"
      end
    end
  end

  test do
    system "#{bin}/cub-scout", "version"
  end
end
