# This file was generated by GoReleaser. DO NOT EDIT.
cask "cub-scout" do
  version "2.11.0"

  on_macos do
    on_arm do
      sha256 "57d37b3d7c1186b8c4bdd3dbbe7d53cf78eb8cd7312d8f133e8f984577c4f04c"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "71141953c32cd69811a1a45b5e759973cfbfbadb4b78cfc23c4ac7e2edf7a596"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "92cfe1a08efa2470aa04dfdfb6024e7be25df91af4cef232d97973cc5529ac07"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f9c2671043e08f659bfb490a966788b20b08509374c296b0a7522c2a994f0f9b"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cub-scout"
  desc "Explore and map GitOps in your clusters"
  homepage "https://confighub.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cub-scout"
  binary "kubectl-cub_scout"

  # No zap stanza required
end
