# This file was generated by GoReleaser. DO NOT EDIT.
cask "cub-scout" do
  version "2.13.1"

  on_macos do
    on_arm do
      sha256 "e0131aebe87aa9619a3e3853a81cbde565f336224a907eaa4a5d72615894458e"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "62fd08a417b10b77a077ee32fc36e4b7743fc03c99f3084178c849b5426e0ac6"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6954f920f68c956d9389c1a1917074cf7f03b012ae0174c3ed875df3786ae63d"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb8ce245e312fa186fb1bb535502268caa74dacc873fa00f4321fcd671166bcf"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cub-scout"
  desc "GitOps explorer for agents: read-only evidence from your clusters"
  homepage "https://confighub.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cub-scout"
  binary "kubectl-cub_scout"

  # No zap stanza required
end
