# This file was generated by GoReleaser. DO NOT EDIT.
cask "cub-scout" do
  version "2.6.0"

  on_macos do
    on_intel do
      sha256 "e6604db4f66c98cff61f2f9a077df784cf189f4e76116398b164f785a6ea0e17"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5844d0e8d6770746d393837ace24d6d7dfd77bec50289ddd466f4ef7e600061"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3da60358bb129a5de53fcb97216572262b0015b1708d750523d4460ea0f9d9a1"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b6f11771e938cefad982ae3ebd4c3f8779c4d9ea802975bcc8c5ae32b9cbfe0"
      url "https://github.com/confighub/cub-scout/releases/download/v#{version}/cub-scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cub-scout"
  desc "Explore and map GitOps in your clusters"
  homepage "https://confighub.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cub-scout"
  binary "kubectl-cub_scout"

  # No zap stanza required

end
